[build]
  command = "pip install -r requirements.txt"
  environment = { RUSTUP_INIT_SKIP_PATH_CHECK = "yes" }

[build.environment]
  RUSTUP_INIT_SKIP_PATH_CHECK = "yes"

[[plugins]]
  package = "netlify-plugin-rust"

[plugins.inputs]
  rustup = { toolchain = "stable" }
